core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index , name='index'),
	path('dashboard', views.welcome , name='welcome'),
	path('<int:user_id>/setup', views.setup, name='setup'),
	path('<int:user_id>/assignment', views.new_assignment, name='new_assignment'),
]

smm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.views import (
	index,
	)

from accounts.views import (login_view, logout_view, register_view)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
	# path('', index, name='index'),
	path('login/',login_view, name='login' ),
	path('logout/', logout_view, name='logout'),
	path('register/', register_view, name='register'),

]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from datetime import timedelta
def return_date_time():
		now = timezone.now()
		return now + timedelta(days=3)

# Create your models here.
class interested(models.Model):
	TYPE_LIST = (
		('Blogger', 'blogger'),
		('Youtuber', 'youtuber'),
		('Local Business', 'local_business'),
		('Other', 'other'),
		)
	
	email_address 			=			models.EmailField(max_length=254, blank=False, null=False)

	interested_in			=			models.CharField(max_length=20, choices=TYPE_LIST, default=TYPE_LIST[0][0])

	timestamp				=			models.DateTimeField(auto_now=False, auto_now_add=True)
	updated					=			models.DateTimeField(auto_now=True, auto_now_add=False)

	def __str__(self):
		return(self.email_address)

	class Meta:
		ordering	 		=			["-timestamp", "-updated"]
		verbose_name 		= 			"Interested Person"
		verbose_name_plural = 			"Interested People"

class clientele(models.Model):
	CLIENT_LIST = (
		('Blog', 'blog'),
		('Youtube', 'youtube'),
		('Local Business', 'local_business'),
		('Other', 'other'),
		)

	client					=			models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
	business_url			=			models.URLField()
	business_type			=			models.CharField(max_length=20, choices=CLIENT_LIST, default=CLIENT_LIST[0][0])
	timestamp				=			models.DateTimeField(auto_now=False, auto_now_add=True)
	updated					=			models.DateTimeField(auto_now=True, auto_now_add=False)

	def __str__(self):
		return(self.business_type + " by " + str(self.client))

	class Meta:
		ordering	 		=			["-timestamp", "-updated"]
		verbose_name 		= 			"Client"
		verbose_name_plural = 			"clientele"

class assignment(models.Model):
	ASSIGNMENT_STATUS = (
		('InReview', 'inreview'),
		('Error', 'error'),
		('Working', 'working'),
		('Completed', 'completed'),
		('Rejected', 'rejected'),
		)

	# Add a new field for user. replace it with client.
	# and for client, connect with with clientele

	user					=			models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
	client 					=			models.ForeignKey('clientele', related_name='assignments', on_delete=models.CASCADE, default=1)

	content_url				=			models.URLField()
	due_date				=			models.DateTimeField(default=return_date_time)
	status					=			models.CharField(max_length=20, choices=ASSIGNMENT_STATUS, default=ASSIGNMENT_STATUS[0][0])

	timestamp				=			models.DateTimeField(auto_now=False, auto_now_add=True)
	updated					=			models.DateTimeField(auto_now=True, auto_now_add=False)

	def __str__(self):
		return( str(self.user) +" "+ str(self.client) +" "+ self.status)


	class Meta:
		ordering	 		=			["-timestamp", "-updated"]
		verbose_name 		= 			"Assignment"
		verbose_name_plural = 			"Assignments"

core/forms.py
from django import forms
from django.core.validators import validate_email

from .models import interested, assignment, clientele

# Form for "interested"
class InterestedForm(forms.ModelForm):
    class Meta:
        model = interested
        fields = [
        'email_address',
        'interested_in',
        ]

    def clean_contact(self):
        this_email = self.cleaned_data.get('email_address')
        this_interest = self.cleaned_data.get('interested_in')
        try:
            validate_email(this_email)
        except forms.ValidationError:
            raise forms.ValidationError("Please enter a Valid Email address")

        existing_email = interested.objects.filter(email_address=this_email, interested_in=this_interest)

        if existing_contact:
            print("CONFLICT OF EMAILS")
            raise forms.ValidationError("You already submitted a request with these credentials")
        else:
            print("NO CONFLICT FOUND")
            return this_email

    def __init__(self, *args , **kwargs):
        super(InterestedForm, self).__init__(*args, **kwargs)
        self.fields["email_address"].help_text = "Please expect our email with in 24 hours."
        self.fields["email_address"].label = "Your Email Addresss"
        self.fields["interested_in"].help_text = "Please expect our email with in 24 hours."
        self.fields["interested_in"].label = "Your Email Addresss"


class assignmentForm(forms.ModelForm):
    class Meta:
        model = assignment
        fields = [
        'content_url',
        ]
    def __init__(self, *args, **kwargs):
        super(assignmentForm, self).__init__(*args, **kwargs)
        self.fields["content_url"].help_text = "Please Enter Your Business URL. (Youtube channel, or Blog URL)"
        self.fields["content_url"].label = "Content URL"


class clienteleForm(forms.ModelForm):
    class Meta:
        model = clientele
        fields = [
        'business_type',
        'business_url',
        ]

    def __init__(self, *args , **kwargs):
        super(clienteleForm, self).__init__(*args, **kwargs)
        self.fields["business_url"].help_text = "Please Enter Your Business URL. (Youtube channel, or Blog URL)"
        self.fields["business_url"].label = "Business URL"
        self.fields["business_type"].help_text = "Your Content type"
        self.fields["business_type"].label = "Content Type"

core/views.py
from django.shortcuts import render, get_object_or_404
from django.http import (
	Http404, HttpResponse, HttpResponsePermanentRedirect, HttpResponseRedirect,
)
from django.urls import reverse

from . models import interested, clientele, assignment
from .forms import InterestedForm, clienteleForm, assignmentForm

# LANDING PAGE
def index(request):
	context = {
		'show_last_div' : False,
	}

	return render(request, 'landing.html', context)

# HOMEPAGE FOR PAYING CUSTOMER.
def welcome(request):
	if request.user.is_authenticated:
		pass
	else:
		return HttpResponseRedirect(reverse('core:index'))
	# print(request.user.id)
	client_assignment = assignment.objects.filter(user_id=request.user.id)
	

	if client_assignment.count() == 0:
		client_assignment = None

	context = {
		'client_assignment' : client_assignment,
		'show_last_div' : False,
	}

	return render(request, 'core/welcome.html', context)

# PAGE TO SETUP ACCOUNT. REDIRECT AFTER FIRST REGISTER.
def setup(request, user_id=None):

	if request.method == 'POST':
		form = clienteleForm(request.POST or None)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.client_id = user_id
			instance.save()
			return HttpResponseRedirect(reverse('core:welcome'))
	else:
		form = clienteleForm()


	context = {
		'form' : form,
		"tab_text": "Confirm.",
	}
	return render(request, 'core/setup.html', context)

# PAGE TO CREATE A NEW ASSIGNMENT
def new_assignment(request, user_id=None):

	if request.method == 'POST':
		form = assignmentForm(request.POST or None)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.user_id = user_id
			instance.save()

			return HttpResponseRedirect(reverse('core:welcome'))
	else:
		form = assignmentForm()
	context = {
		'form' : form,
		"tab_text": "Confirm.",
	}
	return render(request, 'core/new_assignment.html', context)

core/templates/core/new_assignment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
The doctor will see you now! | {{ block.super }}
{% endblock %}

{% block head_extras %}
{{ form.media }}
{% endblock %}

{% block content_2 %}

<!-- <div style="margin-top: 100px"></div> -->
<div style="margin-top: 100px"></div>

<div class="row">
	<div class="col">
		<h1 class="emoji-header-center">🛎</h1>	
		<h3>{{top_text}}</h3>
		<h3><small>{{form_text}}</small></h3>
	</div>
</div>
<div class="row">
	<div class="col">
		<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
			{{ form|crispy }}
			<input type='submit' class='btn btn-outline-primary btn-lg' value='{{ tab_text }}'/>
		</form>
	</div>
</div>
<div style="margin-top: 100px"></div>

<!-- <div style="margin-top: 100px"></div> -->
{% endblock %}

core/templates/core/setup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
The doctor will see you now! | {{ block.super }}
{% endblock %}

{% block head_extras %}
{{ form.media }}
{% endblock %}

{% block content_2 %}

<!-- <div style="margin-top: 100px"></div> -->
<div style="margin-top: 100px"></div>

<div class="row">
	<div class="col">
		<h1 class="emoji-header-center">🛎</h1>	
		<h3>{{top_text}}</h3>
		<h3><small>{{form_text}}</small></h3>
	</div>
</div>
<div class="row">
	<div class="col">
		<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
			{{ form|crispy }}
			<input type='submit' class='btn btn-outline-primary btn-lg' value='{{ tab_text }}'/>
		</form>
	</div>
</div>
<div style="margin-top: 100px"></div>

<!-- <div style="margin-top: 100px"></div> -->
{% endblock %}

core/templates/core/welcome.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
The doctor will see you now! | {{ block.super }}
{% endblock %}

{% block head_extras %}
{{ form.media }}
{% endblock %}

{% block content_2 %}


<!-- <div style="margin-top: 100px"></div> -->


<div class="row">
	<div class="col">
		<p style="float: right;">
			<a href="{% url 'core:new_assignment' user_id=request.user.id %}">
				New order
			</a>
		</p>
	</div>
</div>
<div class="row">
	<div class="col">
		<h1 class="emoji-header-center">🏗</h1>	
		<h3 class="text-center">Hi {{request.user.username}}</h3>
		<h3 class="text-center">
			<small>
				you currently have {{client_assignment|length}} orders in progress.
			</small>
		</h3>
	</div>
</div>
<div style="margin-top: 40px"></div>

<div class="row">
	<div class="col">
		<table class="table">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">Delivery Date</th>
					<th scope="col">Status</th>
					<th scope="col">Delivery</th>
				</tr>
			</thead>
			<tbody>
				{% for assignment in client_assignment %}
				<tr>
					<th scope="row">{{forloop.counter}}</th>
					<td>{{assignment.due_date}}<br><small>{{assignment.due_date|timeuntil}} left</small></td>
					<td>{{assignment.status}}</td>
					<td><span style="color: gray">Download</span></td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
<br>
<div class="row">
	<div class="col">
		<h1 class="emoji-header-center">🏘</h1>	
		<!-- <h3 class="text-center">Hi {{request.user.username}}</h3> -->
		<h3 class="text-center">
			<small>
				<a href="">
					Click Here to see all previous Orders.
				</a>
			</small>
		</h3>
	</div>
</div>
<div style="margin-top: 100px"></div>


<!-- {{client_assignment }} -->


<!-- <div style="margin-top: 100px"></div> -->
{% endblock %}