core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index , name='index'),
	path('dashboard', views.welcome , name='welcome'),
	path('<int:user_id>/setup', views.setup, name='setup'),
	path('<int:user_id>/assignment', views.new_assignment, name='new_assignment'),
]

smm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.views import (
	index,
	)

from accounts.views import (login_view, logout_view, register_view)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
	# path('', index, name='index'),
	path('login/',login_view, name='login' ),
	path('logout/', logout_view, name='logout'),
	path('register/', register_view, name='register'),

]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	{% block other_meta %}

	{% endblock %}

	<title>{% block title %}Social Media Managing{% endblock %}</title> <!-- MAX 70 Chars-->

	<!-- Bootstrap core CSS -->
	<link href="{% static 'base/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

	<!-- Custom styles for this template -->
	<link href="{% static 'base/css/one-page-wonder.css' %}" rel="stylesheet">

	<!-- Custom fonts for this template -->
	<link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

	<style type="text/css">
	.emoji-header {
		font-size: 100px !important;
	}
	.emoji-header-center {
		font-size: 100px !important;
		text-align: center;
	}</style>

	{% block head_extras %}
	{% endblock %}

	{% if production %}
	{% endif %}

</head>

<body>

	<!-- Navigation -->
	{% include 'navbar.html' %}
	
	<!-- <div style="margin-top: 200px"></div> -->

	{% block content_1 %}
	{% endblock %}

	<div class="col-lg-9 col-md-9" style="padding: 50px">{% block content_header %}{% endblock %}</div>
	<div class="col-lg-3 col-md-3"></div>


	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-2"></div>
			<div class="col-lg-6 col-md-8 col-sm-12">
				<!-- content -->
				{% block content_2 %}
				{% endblock %}
			</div>
			<div class="col-lg-3 col-md-3"></div>
		</div>
	</div>


	<!-- Footer -->
	
	{% include 'footer.html' %}

	<!-- Bootstrap core JavaScript -->
	<script src="{% static 'base/vendor/jquery/jquery.min.js' %}"></script>
	<script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

templates/footer.html
<footer class="py-5 bg-dark">
	<div class="container">
		<p class="text-center" style="font-size: 60px">👨‍💻</p>
		<!-- /. welcome emoji -->
		<h4 class="text-center text-white">
			Hi, I am Ali.
		</h4>
		<!-- /. my intro -->
		<p class="m-0 text-center text-white">
			I am a Solo Maker and I created, developed & Maintain this website. I go by AliCoderMaker on 
			<a target="_blank" href="https://www.twitter.com/AliCoderMaker">Twitter</a>, 
			<a target="_blank" href="https://www.instagram.com/AliCoderMaker">Instagram</a> and 
			<a target="_blank" href="https://www.facebook.com/AliCoderMaker">Facebook</a>.
			<br>Copyright &copy; Ali Khundmiri 2018
		</p>
		<!-- /. my details -->
	</div>
	<!-- /.container -->
</footer>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>One Page Wonder - Start Bootstrap Template</title>

	<!-- Bootstrap core CSS -->
	<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

	<!-- Custom fonts for this template -->
	<link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

	<!-- Custom styles for this template -->
	<link href="css/one-page-wonder.min.css" rel="stylesheet">

</head>

<body>

	<!-- Navigation -->
	<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
		<div class="container">
			<a class="navbar-brand" href="#">Start Bootstrap</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<a class="nav-link" href="#">Sign Up</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Log In</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<header class="masthead text-center text-white">
		<div class="masthead-content">
			<div class="container">
				<h1 class="masthead-heading mb-0">One Page Wonder</h1>
				<h2 class="masthead-subheading mb-0">Will Rock Your Socks Off</h2>
				<a href="#" class="btn btn-primary btn-xl rounded-pill mt-5">Learn More</a>
			</div>
		</div>
		<div class="bg-circle-1 bg-circle"></div>
		<div class="bg-circle-2 bg-circle"></div>
		<div class="bg-circle-3 bg-circle"></div>
		<div class="bg-circle-4 bg-circle"></div>
	</header>

	<section>
		<div class="container">
			<div class="row align-items-center">
				<div class="col-lg-6 order-lg-2">
					<div class="p-5">
						<img class="img-fluid rounded-circle" src="img/01.jpg" alt="">
					</div>
				</div>
				<div class="col-lg-6 order-lg-1">
					<div class="p-5">
						<h2 class="display-4">For those about to rock...</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section>
		<div class="container">
			<div class="row align-items-center">
				<div class="col-lg-6">
					<div class="p-5">
						<img class="img-fluid rounded-circle" src="img/02.jpg" alt="">
					</div>
				</div>
				<div class="col-lg-6">
					<div class="p-5">
						<h2 class="display-4">We salute you!</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section>
		<div class="container">
			<div class="row align-items-center">
				<div class="col-lg-6 order-lg-2">
					<div class="p-5">
						<img class="img-fluid rounded-circle" src="img/03.jpg" alt="">
					</div>
				</div>
				<div class="col-lg-6 order-lg-1">
					<div class="p-5">
						<h2 class="display-4">Let there be rock!</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Footer -->
	<footer class="py-5 bg-black">
		<div class="container">
			<p class="m-0 text-center text-white small">Copyright &copy; Your Website 2018</p>
		</div>
		<!-- /.container -->
	</footer>

	<!-- Bootstrap core JavaScript -->
	<script src="vendor/jquery/jquery.min.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

templates/landing.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
The doctor will see you now! | {{ block.super }}
{% endblock %}

{% block head_extras %}
{{ form.media }}
{% endblock %}

{% block content_1 %}

<!-- <div style="margin-top: 100px"></div> -->

<header class="masthead text-center text-white">
	<div class="masthead-content">
		<div class="container">
			<h1 class="masthead-heading mb-0">Creating content for you</h1>
			<h2 class="masthead-subheading mb-0">Helping You stay focused on your skills.</h2>
			<a href="#" class="btn btn-primary btn-xl rounded-pill mt-5">Learn More</a>
		</div>
	</div>
	<div class="bg-circle-1 bg-circle"></div>
	<div class="bg-circle-2 bg-circle"></div>
	<div class="bg-circle-3 bg-circle"></div>
	<div class="bg-circle-4 bg-circle"></div>
</header>

<section>
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-6 order-lg-2">
				<div class="p-5">
					<img class="img-fluid rounded-circle" src="{% static 'base/img/01.jpg' %}" alt="">
				</div>
			</div>
			<div class="col-lg-6 order-lg-1">
				<div class="p-5">
					<h2 class="display-4">For those about to rock...</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
				</div>
			</div>
		</div>
	</div>
</section>

<section>
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-6">
				<div class="p-5">
					<img class="img-fluid rounded-circle" src="{% static 'base/img/02.jpg' %}" alt="">
				</div>
			</div>
			<div class="col-lg-6">
				<div class="p-5">
					<h2 class="display-4">We salute you!</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
				</div>
			</div>
		</div>
	</div>
</section>

<section>
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-6 order-lg-2">
				<div class="p-5">
					<img class="img-fluid rounded-circle" src="{% static 'base/img/03.jpg' %}" alt="">
				</div>
			</div>
			<div class="col-lg-6 order-lg-1">
				<div class="p-5">
					<h2 class="display-4">Let there be rock!</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
				</div>
			</div>
		</div>
	</div>
</section>

<section>
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-6">
				<div class="p-5">
					<!-- <img class="img-fluid rounded-circle" src="{% static 'base/img/02.jpg' %}" alt=""> -->
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
				</div>
			</div>
			<div class="col-lg-6">
				<div class="p-5">
					<h2 class="display-4">Interested?</h2>
					
				</div>
			</div>
		</div>
	</div>
</section>
<!-- <div style="margin-top: 100px"></div> -->
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
	<div class="container">
		<a class="navbar-brand" href="
		{% if request.user.is_authenticated %}
		{% url 'core:welcome' %}
		{% else %}
		{% url 'core:index' %}
		{% endif %}
		">Khund<span style="color: red">media</span></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
				{% if not request.user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'register' %}">Sign Up</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'login' %}">Log In</a>
				</li>
				{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'logout' %}">Log Out</a>
				</li>
				{% endif %}
			</ul>
		</div>
	</div>
</nav>